services:
  postgres:
    container_name: postgres-go
    image: postgres:16.4
    environment:
      POSTGRES_PASSWORD: my_pass
      POSTGRES_USER: postgres
      PGDATA: /data/postgres
    volumes:
      - ./postgres-data:/data/postgres
    ports:
      - 5434:5432